version: "3.1"

services:
  mysql: #Database
    image: mysql:5.6 #Static version Mysql
    container_name: dolphin
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./${DB_SQL_FILE}:/docker-entrypoint-initdb.d/academicdb.sql #import pre create database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
      MYSQL_ROOT_HOST: "%"

  phpmyadmin: #phpmyadmin database GUI
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: mysql

  webserer: #WEB Server for img store
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./imgstore:/usr/share/nginx/html
    ports:
      - "${IMG_STORE_PORT}:80"
    environment:
      - NGINX_PORT=80
